apiVersion: apps/v1
kind: Deployment
metadata:
  name: __SERVICE_NAME__
  labels:
    app.kubernetes.io/name: __SERVICE_NAME__
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: __SERVICE_NAME__
  template:
    metadata:
      labels:
        app.kubernetes.io/name: __SERVICE_NAME__
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 65532
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: __SERVICE_NAME__
          image: __SERVICE_NAME__:0.1.0
          ports:
            - name: http
              containerPort: 8080
          env:
            - name: SERVICE_NAME
              value: __SERVICE_NAME__
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: http://otel-collector.opspilot-system.svc:4318
          readinessProbe:
            httpGet:
              path: /ready
              port: http
          livenessProbe:
            httpGet:
              path: /health
              port: http
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi
          securityContext:
            runAsNonRoot: true
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop: ["ALL"]
