apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: demo-shop
resources:
  - deploy/deployment.yaml
  - deploy/service.yaml
labels:
  - pairs:
      app.kubernetes.io/name: __SERVICE_NAME__
      app.kubernetes.io/part-of: opspilot
